controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Routes

#register
app_register:
  path: /inscription
  controller: App\Controller\RegistrationController::register

#verifier email
app_verify:
  path: /verif/{token}
  controller: App\Controller\RegistrationController::verifUser

#resend email
app_resend:
  path: /resend
  controller: App\Controller\RegistrationController::resendVerification

#login
app_login:
  path: /connexion
  controller: App\Controller\SecurityController::login

#logout
app_logout:
  path: /deconnexion
  controller: App\Controller\SecurityController::logout

#Accueil
app_index:
  path: /
  controller: App\Controller\PageViewController::index

#Produits
app_products:
  path: /tous-nos-instruments
  controller: App\Controller\PageViewController::products
  defaults:
    roles: ["ROLE_USER"]

#Rubriques
app_rubrics:
  path: /nos-rubriques
  controller: App\Controller\PageViewController::rubriques
  defaults:
    roles: ["ROLE_USER"]
#Profil
app_profil:
  path: /profil
  controller: App\Controller\ProfileController::profile

#Dashboard
app_dashboard:
  path: /admin/dashboard
  controller: App\Controller\DashboardController::dashboard
  defaults:
    roles: ["ROLE_ADMIN"]
